version: '3'
services:
  furigana-web-app-client:
    build: client
    image: "hatcha82/furiganahub-vuejs-app:latest"
    ports:
     - "80:80"
    depends_on:
     - furigana-web-api-server
  furigana-web-api-server:
    build: server
    image: "hatcha82/furiganahub-api:latest"
    ports:
     - "8080:8080"
volumes:
    jpntuto_mariadb_data:
    jpntuto_mariadb_config:
